services:
  web:
    build: ./
    image: web
    container_name: web
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/home/node/app/prisma
      - ./public:/home/node/app/public
      - ./scripts:/home/node/app/scripts
      - ./src:/home/node/app/src
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=200' -c 'log_statement=all'
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:
